apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: echo
  name: echo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - image: troydai/echoserver:v1
        imagePullPolicy: IfNotPresent
        name: echoserver
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
